build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy-prod:
  stage: deploy
  script:
    - cd /home/gitlab-runner/source/webapp
    - npm install
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
