stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: repository.devpbteam.com:5000/lunch_webapp:$IMAGE_VERSION

cache:
  paths:
    - node_modules/

app-build:
  stage: build
  script: npm install 
  only:
    - merge_request
    - main