stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: repository.devpbteam.com:5000/lunch_webapp:$IMAGE_VERSION

cache:
  paths:
    - node_modules/

build:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - cd /home/cherry/source/webapp
    - sudo docker container ls -a
    - sudo docker build . -t $IMAGE_NAME
    - sudo docker push $IMAGE_NAME
