version: '3.8'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'

  webapp:
    image: repository.devpbteam.com:5000/lunch_webapp:latest
    container_name: webapp
    ports:
      - 9000:9000
