version: "3"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    hostname: app
    ports:
      - 9000:9000
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    environment:
      TZ: 'Asia/Seoul'
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx/html:/etc/nginx/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/logs:/var/log/nginx"
    depends_on:
      - webapp
